version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: zoo
      MYSQL_USER: zoo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./src/data/seed.sql:/data/seed.sql
    ports:
      - 3306:3306
